### ISSUE TITLE
"i" icons supermiposed on descriptions, in IE 11

### ISSUE THREAD

**Issue by claremacrae** [davidearl/jcomma#4]
IE 11.589.10586.0 - Windows 10.

**Comment by claremacrae** [comment]
Screenshot (hopefully):

![2016-09-21_22_49_12-jcomma_ a csv converter](https://cloud.githubusercontent.com/assets/4840096/18730351/d40d8844-804d-11e6-9501-b1cb745c7f3a.png)

**Comment by claremacrae** [comment]
As far as I know, I have no content blockers, script blockers or similar....

**Comment by davidearl** [comment]
Thanks - those position: relative elements seem to require an explicit left in the css in IE11. I could only reproduce it intermittently though - it seems like it depends on how long it takes to download the i image.

**Comment by claremacrae** [comment]
Assuming you've deployed it already, yes, it's fixed - thanks!
